[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
simple-agent = "FDUE22UDZUMcGXeDRKJJbNX1GMh4CREWnziam8GkmerY"
solana_gpt_oracle = "4cTXXUpQHbzrLRgXxqkFKFe8oHHjivUzaHP7d78EYTGK"
escrow = "8cCWwrHTFe5V8xDxXZEkrfUquoq3bWUhukEyjPexbJ7y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/fixtures/metadata.so"
upgradeable = false

[[test.genesis]]
address = "DELeGGvXpWV2fqJUhqcF5ZSYMS4JTLjteaAMARRSaeSh"
program = "tests/fixtures/dlp.so"
upgradeable = false
